import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/Card";
import { Grid } from "@mui/material";
import { footerLinks, projects, socialLinks } from "@/data";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Exhibition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={styles.main}
        style={{ backgroundImage: `url("/bg.jpeg")` }}
      >
        <div className={styles.description}>
          <Image
            src="/dp.jpeg"
            alt="Picture of the author"
            width={100}
            height={100}
            style={{ borderRadius: "50%" }}
          />
          <p>
            Tech&nbsp;
            <code className={styles.code}>Exhibition</code>
          </p>
          <div>Design Studio</div>
        </div>

        <Grid
          container
          gap={4}
          className={styles.center}
          style={{ fontSize: 64 }}
        >
          {projects.map((project, index) => (
            <Grid key={index} item xs={12} md={6} lg={2.5}>
              <Card
                title={project.title}
                description={project.description}
                imageUrl={project.imageUrl}
                link={project.link}
              />
            </Grid>
          ))}
        </Grid>

        {/* <div className={styles.grid}>
          {footerLinks.map((link) => (
            <a
              href={link.link}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                {link.title} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>{link.description}</p>
            </a>
          ))}
        </div> */}

        <div className={styles.grid}>
          {socialLinks.map((link, id) => (
            <a
              href={link.link}
              key={id}
              className={styles.card}
              style={{
                border: "0.5px white solid",
                marginLeft: 10,
                marginRight: 10,
              }}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                {link.title} <span>-&gt;</span>
              </h2>
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
